### ISSUE TITLE
Pulumi Github App Filtering No-Ops

### ISSUE THREAD

**Issue by liamawhite** [pulumi/service-requests#30]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

In some of our projects we have 30+ stacks. If we make changes to one or two the Pulumi Github App comments about all of them which makes it difficult to wade through the noise. We only want to see ones where there is actually a diff. Currently, it will comment saying its read the stack references.

### Affected area/feature

Pulumi Service/Github

**Comment by vubogovich** [comment]
Our team is very interested in it as well! Looks like very simple and valuable improvement - how can we move it forward?

**Comment by blampe** [comment]
@liamawhite @vubogovich would you like to hide read operations in general, or only updates that are *exclusively* reads? In other words, we can definitely ignore this case

```
Name		Type		Operation
foo		bar		read
biz		baz		read	
```	

but how should we handle:

```
Name		Type		Operation
foo		bar		replaced
biz		baz		read		
```

Should this be displayed as-is, or should we omit the “read” in favor of the more compact:

```
Name		Type		Operation
foo		bar		replaced
```

Asking because I've also seen updates with a lot of StackReferences which can be a dozen reads with one real operation, which felt like a lot of wasted space on the PR.

**Comment by liamawhite** [comment]
I dont have a strong opinion either way. We don't have that many reads per stack so it's not an issue for us.

**Comment by blampe** [comment]
Hey @aviflat, totally agree this is spammy! I'm currently looking into our GH app and should have a fix available for this soon. 

If you have an opinion on my comment above (https://github.com/pulumi/service-requests/issues/30#issuecomment-1170778472) that would help me dial in the functional changes and get this out faster -- let me know what you think.

**Comment by aviflat** [comment]
Thanks @blampe that’s great to hear. My opinion is to omit the read operations. Thank you!

**Comment by aviflat** [comment]
Thank you!

**Comment by aviflat** [comment]
Just checking — was this already deployed? Because if so something might be off, as I just opened a new PR in my org-internal private repo, and I’m still getting the np-op comments:

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/99206340/178847269-4e591ae5-9c5a-4a44-9bf4-aae6c3ee8743.png">

This was just a few minutes ago.

**Comment by blampe** [comment]
Hey @aviflat - sorry, GitHub closes these issues automatically when they're merged, but not yet deployed. The change should be live now - can you confirm the fix is working for you?

**Comment by aviflat** [comment]
No worries — looking good now! Thanks!

**Comment by robertf224** [comment]
@blampe any thoughts on being able to exclude read operations in general (including when there are writes)

**Comment by blampe** [comment]
> @blampe any thoughts on being able to exclude read operations in general (including when there are writes)?  or at least sectioning them off below or something?  sort of just clutters the output
> 
> 
> 
> alternatively since we're using github actions seems like I could just use the `comment-on-pr` argument (assuming the action doesn't automatically append the `--show-reads` flag)

We discussed this internally and decided if we did take this on we would also need to re-think how we display reads in other places like the CLI and website. Ultimately, hiding the reads on GH alone might be convenient, but it opens the door for a lot of inconsistency and confusion so we decided against it for now.

Re: the GitHub action, these comments can come from that action or the GitHub app, if you installed it. If the comments aren't richly formatted they're probably coming from the action.

**Comment by robertf224** [comment]
makes sense.  fwiw the cli doesn't show reads by default, you need to pass it the `--show-reads` [argument](https://www.pulumi.com/docs/reference/cli/pulumi_preview/?utm_campaign=&utm_term=&utm_medium=ppc&utm_source=adwords&hsa_grp=136279040283&hsa_cam=15160582074&hsa_mt=&hsa_net=adwords&hsa_ver=3&hsa_acc=1926559913&hsa_ad=597773591016&hsa_src=g&hsa_tgt=dsa-1655465285681&hsa_kw=&gclid=Cj0KCQjw_7KXBhCoARIsAPdPTfh6MnPTTbGta-Vb9Ph-e5ao3LkpK-Kk6t1NzfWw_QNxh9zYCA67LOUaApmBEALw_wcB#options).  the website and github app don't respect this argument, ideally it would propagate through?  or at the very least if reads displayed in a separate section rather than being mixed with writes (where it becomes harder to see what's actually happening if you have several stack references, i.e. see example below)
<img width="570" alt="Screen Shot 2022-08-05 at 3 20 09 PM" src="https://user-images.githubusercontent.com/671815/183146418-64e2376f-84b9-40e9-ad0b-972cdbbb9747.png">

**Comment by vubogovich** [comment]
@blampe Sorry for the late reply. I'm for ignoring updates that are exclusively reads. When there are updates it would be useful to see that they could be triggered with other stacks rather than a local change.
